# Generated by Django 5.1.4 on 2024-12-14 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_tag', models.CharField(max_length=31)),
                ('cat_name', models.CharField(max_length=63)),
                ('cat_description', models.CharField(max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.IntegerField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=64, null=True)),
                ('ticket_subject', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_tag', models.CharField(max_length=31)),
                ('unit_name', models.CharField(max_length=63)),
                ('unit_okei', models.CharField(blank=True, default='000', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=31)),
                ('name', models.CharField(max_length=63)),
                ('description', models.TextField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img', models.ImageField(blank=True, null=True, upload_to='products')),
                ('ico', models.ImageField(blank=True, default='noico.png', null=True, upload_to='products')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categories')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.units')),
            ],
        ),
    ]
